In [1]:
# Uncoomment as needed. Downloads dependencies.

# downloads requirements inside this environment
# %pip install -r requirements.txt

# downloads requirements into the PC itself
# !pip install -r requirements.txt

In [2]:
import numpy as np
import pandas as pd
import itertools
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
hbnd_df = pd.read_csv("./src/h_bnd.csv")
sasa_ub_df = pd.read_csv("./src/sasa_unbnd.csv")
otw_binding_df = pd.read_csv("./src/otw_binding.csv")
sasa_bnd_df = pd.read_csv("./src/sasa_bnd.csv")
sasa_bndwh_df = pd.read_csv("./src/sasa_bnd_whole.csv")
sasa_bnd_fcc_df = pd.read_csv("./src/sasa_bnd_fcc.csv")

In [4]:
scaler = StandardScaler()
scaled_hbnd = scaler.fit_transform(hbnd_df)
sc_hbnd_df = pd.DataFrame(scaled_hbnd)
sc_hbnd_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.199868,0.515711,0.479093,-0.220779,0.275380,1.166667,0.300150,-0.452187,-0.351095,0.870186,1.347928,0.272195,1.056806,1.228769,0.473118,1.468919,NaN,-0.344258,-0.100205,0.535870
1,1.108358,-2.372269,-0.396491,0.482954,0.275380,-0.722222,1.125563,-1.186990,1.161314,0.085592,-0.646267,0.272195,-0.764152,-0.296600,0.473118,-1.303872,NaN,0.383980,-0.100205,1.389912
2,1.108358,-0.928279,0.479093,-1.628245,0.275380,-0.722222,0.300150,1.752224,-0.351095,0.870186,1.347928,-1.821615,0.146327,0.466085,-0.545906,0.544655,0.473804,-0.344258,NaN,-0.318173
3,-0.708623,-0.206284,-0.396491,-0.924512,1.303466,-0.722222,1.125563,1.017420,1.917519,0.870186,0.350831,NaN,1.967285,-0.296600,-0.545906,-1.303872,0.473804,-0.344258,-0.100205,1.389912
4,1.108358,-0.206284,-0.396491,-0.220779,0.275380,0.222222,-0.525263,-0.452187,-0.351095,0.870186,NaN,-1.821615,-1.674631,1.228769,0.473118,-0.379608,0.473804,1.112217,-0.100205,-1.172215

In [5]:
print(sc_hbnd_df.max().astype(str) + "     " + sc_hbnd_df.min().astype(str))

0       2.016848804946436     -2.525603458446437
1     1.9597003678917069     -3.0942637387763807
2       2.230262776535928     -2.147660451479042
3       1.890419586963519     -3.035710285634849
4      2.3315511514490495     -2.808876584029171
5      2.1111111111111103     -2.611111111111112
6     1.9509757318599086     -3.0015011259383213
7      2.487027043354575     -3.3914005136653285
8      1.917518758995955     -2.6197087270789794
9       1.654780571042197     -2.268190610307838
10     2.3450261470637264     -2.640462512048134
11    2.3660057778120636     -1.8216150678730052
12     1.9672846334406517     -3.495588398262313
13      1.991453913453068     -3.347337428995583
14    2.5111671121015937     -2.5839545646262794
15     1.4689188852229889     -2.228135387697794
16    2.3690177073967145     -2.3690177073967145
17    1.8404543161300067     -3.2572069191941124
18      2.175873670392699     -3.134975880368429
19      1.389912379166786     -2.880300352008281
dtype: object

In [6]:
print(hbnd_df.max().astype(str) + "     " + hbnd_df.min().astype(str))

ALA    11.0     6.0
ARG    11.0     4.0
ASN    11.0     6.0
ASP    11.0     4.0
CYS    11.0     6.0
GLU    11.0     6.0
GLN    11.0     5.0
GLY    12.0     4.0
HIS    11.0     5.0
ILE    11.0     6.0
LEU    11.0     6.0
LYS    11.0     7.0
MET    11.0     5.0
PHE    11.0     4.0
PRO    11.0     6.0
SER    10.0     6.0
THR    11.0     6.0
TRP    11.0     4.0
TYR    11.0     4.0
VAL    10.0     5.0
dtype: object

In [7]:
scaled_sasa_ub = scaler.fit_transform(sasa_ub_df)
sc_sasa_ub_df = pd.DataFrame(scaled_sasa_ub)
sc_sasa_ub_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.441384,-0.835355,-1.111849,-1.919606,-0.605410,-1.118416,-1.216699,-0.334828,-0.766414,-0.829482,-0.316460,-0.683671,NaN,-0.950283,-0.083965,-0.360104,-0.510945,-0.603737,-0.721731,-1.403299
1,-0.491258,-0.257499,-1.052298,-0.584169,0.704927,-1.329820,-0.829858,-1.624188,-0.864299,1.250216,-1.172094,0.238264,-0.322382,-0.917248,-1.576561,-0.138436,NaN,0.058275,-0.520962,0.172029
2,1.396358,1.711676,1.742959,1.133086,0.718241,-0.035871,3.937579,0.336038,-1.415303,1.210541,-0.299045,1.146584,1.702432,-0.662056,-0.793486,-0.520878,-0.410785,-0.186579,NaN,-0.102525
3,-0.802705,-0.513096,0.885495,0.810723,-0.630501,-1.437084,-1.190185,2.178055,-1.236438,1.956218,-0.440269,NaN,-0.161490,-0.345109,-0.023059,1.046520,0.703706,-0.145533,1.474733,-0.412002
4,-1.543321,-0.652125,0.102321,0.204055,1.416039,0.121732,-0.493913,0.548179,0.446072,0.094693,NaN,-1.498957,0.120764,-0.097414,0.280350,-1.995284,1.967145,-1.270297,0.865505,2.401294

In [8]:
sasa_bnd_df.head()

,ALA,ARG,ASN,ASP,CYS,GLU,GLN,GLY,HIS,ILE,LEU,LYS,MET,PHE,PRO,SER,THR,TRP,TYR,VAL
0,3021.536621,3144.528809,3074.209961,3089.358154,3147.086670,3188.895752,3225.294434,3116.558105,3185.936768,3167.329102,3222.031738,3155.372314,3235.078125,3177.545410,3189.553467,3164.505127,NaN,3142.773926,3170.345703,3146.637207
1,3212.853271,3269.848145,3188.226318,3118.199219,3120.187988,3223.502197,3172.688721,3169.795166,3192.484375,3182.640381,3246.260986,3409.857178,3239.344238,3183.604980,3285.399414,3240.848633,NaN,3230.986572,3321.089600,3117.419678
2,3114.270264,3154.209473,3160.346436,3263.613037,3258.334961,3157.910156,3202.566162,3302.836670,3221.173828,3348.243408,3152.132568,3098.444092,3367.024414,3231.333008,3252.458984,3169.530273,3198.330566,3072.256104,NaN,3312.014893
3,3224.113037,3134.017578,3128.296631,3188.125732,3119.025146,3153.989990,3174.175293,3149.499268,3245.378174,3149.852783,3169.869629,NaN,3218.083740,3061.395996,3104.155762,3228.522705,3094.011963,3202.609863,3197.997314,3122.395264
4,3106.419434,3112.103271,3084.266113,3088.045166,3166.975830,3116.073730,3117.255371,3211.277832,3043.946289,3052.977295,NaN,3165.277588,3191.004639,3181.317383,3169.155029,3105.623779,3190.784180,3267.276611,3186.772217,3063.746094

In [9]:
scaled_sasa_bnd = scaler.fit_transform(sasa_bnd_df)
sc_sasa_bnd_df = pd.DataFrame(scaled_sasa_bnd)
sc_sasa_bnd_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,-2.254252,-0.885115,-1.350067,-1.245031,-0.420769,-0.222357,0.142187,-0.784976,0.146981,-0.358625,0.297344,-0.796653,0.417248,-0.214499,0.050752,-0.166388,NaN,-1.015660,-0.463707,-0.306507
1,0.629108,0.544708,0.252964,-0.875963,-0.751828,0.295769,-0.503050,-0.043123,0.252753,-0.144094,0.638269,2.325390,0.473332,-0.127272,1.355506,0.874863,NaN,0.144694,1.605004,-0.745053
2,-0.856650,-0.774664,-0.139017,0.984842,0.948433,-0.686271,-0.136587,1.810796,0.716209,2.176217,-0.686194,-1.495053,2.151868,0.559767,0.907087,-0.097850,0.608994,-1.943255,NaN,2.175763
3,0.798806,-1.005042,-0.589627,0.018860,-0.766140,-0.744963,-0.484816,-0.325945,1.107212,-0.603490,-0.436619,NaN,0.193832,-1.886455,-1.111769,0.706749,-1.054777,-0.228575,-0.084234,-0.670371
4,-0.974971,-1.255072,-1.208681,-1.261833,-0.175981,-1.312643,-1.182969,0.534933,-2.146767,-1.960840,NaN,-0.675134,-0.162161,-0.160202,-0.226932,-0.969471,0.488637,0.622055,-0.238280,-1.550678

In [10]:
sasa_bndwh_df.head()

,ALA,ARG,ASN,ASP,CYS,GLU,GLN,GLY,HIS,ILE,LEU,LYS,MET,PHE,PRO,SER,THR,TRP,TYR,VAL
0,15013.80566,15187.99805,14995.32129,15091.66895,15360.16602,15147.07520,15234.72559,15060.15527,15141.74805,15168.52148,15205.26270,15288.55469,15372.57129,15318.64551,15108.43262,15275.40625,NaN,15262.05273,15324.79883,15239.16699
1,15550.94434,15718.09277,15178.14941,15216.44922,15300.75977,15211.94238,15104.35254,15187.65723,15316.82129,15337.06152,15189.81445,15497.25586,15382.91504,15322.43262,15443.46777,15275.77148,NaN,15279.24316,15323.65039,15072.27637
2,15099.05957,15240.80469,15552.99219,15404.21484,15363.73535,15204.66016,15308.00098,15371.30469,15188.42773,15186.77637,15060.02930,15391.24023,15350.22070,15271.40723,15200.29688,15120.69043,15362.31250,15081.91699,NaN,15487.28906
3,15226.06250,15434.43848,14903.42383,15355.14355,15021.98730,15100.66699,15160.86914,15250.91406,14991.44238,15107.80078,15061.96875,NaN,15109.74414,15090.02148,15121.12305,15392.16992,15211.03809,15237.51465,15231.09375,15050.98047
4,15129.85449,15144.76953,15119.16895,15161.94043,15263.42480,15221.79004,15211.48926,15408.74902,15333.42773,15032.53027,NaN,15066.71973,15110.49414,15145.00586,15319.52539,15029.32031,15433.24316,15333.58301,15504.08203,15075.31738

In [11]:
scaled_sasa_bndwh = scaler.fit_transform(sasa_bndwh_df)
sc_sasa_bndwh_df = pd.DataFrame(scaled_sasa_bndwh)
sc_sasa_bndwh_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,-1.635461,-0.711559,-1.342495,-1.071414,0.883897,-0.860022,-0.217907,-1.213766,-0.572445,-0.622919,-0.366816,0.073110,0.887094,0.690503,-0.742120,0.284467,NaN,0.000521,0.469155,0.128992
1,2.253512,2.855596,-0.205288,-0.243607,0.434891,-0.279334,-1.332885,-0.270185,0.917969,0.568506,-0.472580,1.449777,0.955344,0.717002,1.552404,0.287242,NaN,0.131522,0.460893,-0.967782
2,-1.018208,-0.356208,2.126266,1.002052,0.910875,-0.344524,0.408759,1.088902,-0.175057,-0.493873,-1.361129,0.750460,0.739621,0.359969,-0.112978,-0.890881,1.078153,-1.372213,NaN,1.759604
3,-0.098686,0.946808,-1.914105,0.676507,-1.672134,-1.275466,-0.849543,0.197949,-1.852010,-1.052159,-1.347851,NaN,-0.847085,-0.909219,-0.655209,1.171500,-0.179734,-0.186473,-0.204947,-1.107734
4,-0.795248,-1.002456,-0.572152,-0.605225,0.152705,-0.191178,-0.416629,1.366009,1.059341,-1.584253,NaN,-1.390194,-0.842136,-0.524484,0.703571,-1.585004,1.667961,0.545621,1.758894,-0.947797

In [12]:
sasa_bnd_fcc_df.head()

,ALA,ARG,ASN,ASP,CYS,GLU,GLN,GLY,HIS,ILE,LEU,LYS,MET,PHE,PRO,SER,THR,TRP,TYR,VAL
0,11949.92871,11966.34863,11849.35645,11925.65820,12147.55469,11838.21387,11931.76367,11891.45215,11883.13281,11902.04785,11882.67285,12041.11426,12068.78027,12064.43750,11824.40430,12012.78125,NaN,12036.12012,12048.90625,11986.45703
1,12284.12207,12367.47168,11902.56543,12039.79883,12102.85059,11925.52539,11806.45605,11957.51758,12075.73730,12079.42578,11849.21289,11996.47266,12070.37402,12037.03125,12102.68457,11926.17480,NaN,11969.83789,11909.42578,11860.19043
2,11932.64355,12016.72754,12278.12012,12043.57324,12016.30469,11953.92383,12047.47363,11995.60352,11867.89648,11752.91016,11838.10938,12204.70801,11922.78125,11963.21387,11861.73145,11849.67969,12115.54492,11933.13379,NaN,12094.84961
3,11937.13574,12180.64063,11684.76563,12082.86914,11833.99316,11848.06445,11915.40430,12015.54492,11665.33203,11861.25684,11808.54297,NaN,11779.02539,11921.91406,11913.56152,12070.12695,12029.11133,11931.62500,11926.94727,11876.58008
4,11926.25000,11967.55078,11922.37305,12020.49609,11990.37988,12035.57422,12003.52734,12147.23047,12222.95898,11914.85449,NaN,11827.38281,11843.86426,11890.71484,12051.70508,11851.33496,12208.85742,11998.72949,12225.98047,11914.51758

In [13]:
scaled_sasa_fcc = scaler.fit_transform(sasa_bnd_fcc_df)
sc_sasa_bnd_fcc_df = pd.DataFrame(scaled_sasa_fcc)
sc_sasa_bnd_fcc_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,-0.334967,-0.191726,-0.886313,-0.492145,1.607677,-1.238353,-0.370202,-0.683876,-0.604125,-0.709219,-0.788539,0.535419,0.904619,1.084423,-1.148970,0.326158,NaN,0.791996,0.653038,0.124775
1,2.421213,2.988799,-0.451283,0.478349,1.178626,-0.335143,-1.712899,-0.116727,1.040145,0.903697,-1.059107,0.152041,0.917307,0.834429,1.332783,-0.590787,NaN,0.090456,-0.586082,-0.912829
2,-0.477522,0.207731,2.619209,0.510442,0.347996,-0.041370,0.869654,0.210227,-0.734198,-2.065344,-1.148894,1.940346,-0.257739,0.161082,-0.816080,-1.400679,1.160810,-0.298025,NaN,1.015498
3,-0.440474,1.507406,-2.231989,0.844560,-1.401753,-1.136452,-0.545496,0.381417,-2.463496,-1.080136,-1.387978,NaN,-1.402237,-0.215646,-0.353850,0.933305,0.323819,-0.313994,-0.430424,-0.778146
4,-0.530251,-0.182194,-0.289338,0.314226,0.099180,0.803277,0.398761,1.511890,2.296980,-0.592767,NaN,-1.300087,-0.886029,-0.500239,0.878139,-1.383154,2.064414,0.396249,2.226135,-0.466392

In [14]:
#Main DataFrame containing all the datasets except for binding energy
df = pd.concat([sc_sasa_ub_df, sc_sasa_bnd_df, sc_sasa_bndwh_df , sc_sasa_bnd_fcc_df,sc_hbnd_df], axis=1, ignore_index=False)
df.head(56)

,0,1,2,3,4,5,6,7,8,9,...,10,11,12,13,14,15,16,17,18,19
0,0.441384,-0.835355,-1.111849,-1.919606,-0.605410,-1.118416,-1.216699,-0.334828,-0.766414,-0.829482,...,1.347928,0.272195,1.056806,1.228769,0.473118,1.468919,NaN,-0.344258,-0.100205,0.535870
1,-0.491258,-0.257499,-1.052298,-0.584169,0.704927,-1.329820,-0.829858,-1.624188,-0.864299,1.250216,...,-0.646267,0.272195,-0.764152,-0.296600,0.473118,-1.303872,NaN,0.383980,-0.100205,1.389912
2,1.396358,1.711676,1.742959,1.133086,0.718241,-0.035871,3.937579,0.336038,-1.415303,1.210541,...,1.347928,-1.821615,0.146327,0.466085,-0.545906,0.544655,0.473804,-0.344258,NaN,-0.318173
3,-0.802705,-0.513096,0.885495,0.810723,-0.630501,-1.437084,-1.190185,2.178055,-1.236438,1.956218,...,0.350831,NaN,1.967285,-0.296600,-0.545906,-1.303872,0.473804,-0.344258,-0.100205,1.389912
4,-1.543321,-0.652125,0.102321,0.204055,1.416039,0.121732,-0.493913,0.548179,0.446072,0.094693,...,NaN,-1.821615,-1.674631,1.228769,0.473118,-0.379608,0.473804,1.112217,-0.100205,-1.172215
5,-0.337005,-0.256630,-0.602955,1.408445,0.605510,0.002404,-0.023203,-0.158317,-0.349300,NaN,...,0.350831,-0.774710,0.146327,-0.296600,1.492143,-2.228135,0.473804,0.383980,-0.100205,NaN
6,1.357916,-0.149534,1.730235,-1.101519,-0.198366,-1.135083,1.937820,0.152036,1.580575,1.549609,...,1.347928,-1.821615,0.146327,1.228769,0.473118,0.544655,-0.473804,-0.344258,0.658488,1.389912
7,-0.222113,0.518603,NaN,-0.754566,-1.504821,0.354036,0.045325,-0.065599,0.848171,-1.320680,...,0.350831,-0.774710,0.146327,-0.296600,-0.545906,-0.379608,0.473804,0.383980,-0.858898,-0.318173
8,-0.940664,-0.238521,-1.085072,0.561585,-0.487877,-1.201839,-0.721859,NaN,0.802801,0.578210,...,-0.646267,0.272195,0.146327,-1.059284,-0.545906,1.468919,1.421411,-1.800732,-0.858898,-0.318173
9,-1.315341,0.124813,1.157802,0.201989,-0.793833,0.196504,-0.027478,-0.229627,0.093073,-0.405633,...,0.350831,NaN,-0.764152,1.991454,0.473118,-1.303872,-1.421411,0.383980,-0.100205,0.535870
10,-1.304603,-0.368128,-0.192787,0.319075,0.664042,-0.933641,-1.542970,-1.785182,1.296694,-0.605873,...,-0.646267,0.272195,0.146327,0.466085,0.473118,0.544655,NaN,-0.344258,-0.100205,0.535870
11,1.394942,-0.816397,-0.585574,0.723024,-0.148306,-0.654033,-0.314275,0.935780,-0.587794,-0.885065,...,NaN,-0.774710,1.056806,-1.059284,0.473118,1.468919,-1.421411,1.112217,-0.858898,0.535870
12,-1.340255,0.785255,-0.849094,-0.844330,0.518924,0.908376,0.556960,-0.379146,0.993703,-1.593892,...,-0.646267,NaN,0.146327,-1.059284,1.492143,0.544655,-0.473804,1.112217,0.658488,0.535870
13,-0.578040,0.567615,-0.490451,0.209451,2.292721,-0.655960,-0.773135,NaN,0.282838,-1.964847,...,1.347928,2.366006,0.146327,-1.059284,2.511167,1.468919,-0.473804,0.383980,-0.100205,0.535870
14,0.007678,-1.117396,1.648216,0.621574,-1.205436,NaN,0.545355,-0.010766,-0.859234,-0.614711,...,0.350831,0.272195,-0.764152,-0.296600,-0.545906,-1.303872,1.421411,0.383980,0.658488,0.535870
15,1.268347,-0.261783,0.484316,-1.925605,-0.858323,0.583387,-0.152550,0.793847,-2.061504,0.267530,...,0.350831,0.272195,0.146327,0.466085,-0.545906,-0.379608,NaN,1.112217,2.175874,0.535870
16,-1.254935,-0.543043,-1.089885,-0.697275,0.088184,-0.568383,-0.753114,-2.531899,-2.189604,0.487385,...,-1.643365,0.272195,1.056806,1.991454,-0.545906,0.544655,NaN,0.383980,1.417181,-0.318173
17,1.035517,-1.361032,0.868618,-1.133410,0.480359,1.820882,0.589999,0.921246,-0.856853,0.972458,...,1.347928,0.272195,-0.764152,-0.296600,0.473118,-0.379608,NaN,0.383980,0.658488,1.389912
18,-0.906106,0.603072,-0.835339,0.291817,-0.113593,NaN,-0.722509,-0.607474,-0.261468,0.211960,...,0.350831,0.272195,-0.764152,0.466085,0.473118,-1.303872,-0.473804,0.383980,0.658488,-1.172215
19,NaN,0.229514,0.174441,-0.895057,-0.572567,0.216790,-0.278941,0.467371,0.287324,-0.640028,...,0.350831,-0.774710,0.146327,0.466085,-0.545906,0.544655,-0.473804,1.840454,-1.617590,1.389912
20,0.266079,-0.004072,-1.527163,2.064288,-0.803853,0.387914,-0.294617,-0.524502,-0.718456,-0.620137,...,1.347928,0.272195,1.056806,0.466085,-1.564930,0.544655,0.473804,-0.344258,-0.100205,NaN
21,0.685896,1.301175,-0.058878,NaN,-0.121732,-0.926594,-0.508279,-1.093365,-1.457920,-0.156698,...,-0.646267,-0.774710,-1.674631,-1.059284,0.473118,-0.379608,0.473804,-1.072495,0.658488,0.535870
22,NaN,-1.167089,0.611357,1.338756,1.559174,-0.486269,1.059011,-1.248401,-0.410483,0.763128,...,0.350831,1.319101,0.146327,-0.296600,0.473118,-0.379608,-0.473804,-1.800732,2.175874,0.535870
23,NaN,0.754031,0.546774,1.106245,0.515040,1.692179,-0.008674,0.057863,0.897320,0.308676,...,-1.643365,-1.821615,0.146327,0.466085,1.492143,0.544655,-0.473804,0.383980,0.658488,-0.318173
24,-0.577558,-1.203535,-1.094175,0.603953,-1.124069,-1.533990,-1.346107,-1.161081,1.437624,-1.933780,...,0.350831,-0.774710,-0.764152,-0.296600,-0.545906,0.544655,NaN,1.840454,0.658488,0.535870
25,NaN,0.349524,1.875926,-0.036132,0.760477,-1.136917,2.164455,-0.077650,2.028902,0.322476,...,0.350831,0.272195,-0.764152,-1.821968,0.473118,-0.379608,-0.473804,0.383980,0.658488,-2.026258
26,-0.295670,0.708699,-0.249985,0.214721,-0.063649,NaN,0.955263,-0.662680,0.972722,-0.044229,...,-1.643365,0.272195,-2.585110,-0.296600,-0.545906,-2.228135,-2.369018,-1.800732,-0.100205,-2.880300
27,-0.466618,0.500255,0.030545,0.744398,-0.101243,0.238547,0.920639,1.377874,-0.234796,0.439369,...,-0.646267,NaN,-0.764152,-0.296600,-0.545906,1.468919,2.369018,-1.072495,1.417181,-2.026258
28,0.541010,0.310297,0.129858,0.488587,0.118491,-0.111118,0.550194,0.944805,0.148483,-0.371745,...,0.350831,0.272195,1.056806,0.466085,-0.545906,0.544655,0.473804,1.840454,-0.100205,NaN
29,0.269008,-1.028131,0.118411,-0.588671,0.218361,-1.197105,0.473266,-0.421661,1.202275,-1.369544,...,0.350831,0.272195,0.146327,NaN,1.492143,-0.379608,1.421411,-0.344258,-0.100205,-0.318173
30,0.753253,-0.981611,0.211373,0.845540,-0.558372,-0.293479,-1.497060,0.642715,-0.487453,0.544037,...,-1.643365,NaN,-3.495588,-3.347337,-1.564930,-2.228135,-0.473804,-3.257207,-3.134976,-1.172215
31,0.523306,0.156450,-0.951190,0.593924,0.078088,-0.346812,NaN,-0.828963,-0.372517,-2.400583,...,1.347928,1.319101,0.146327,0.466085,-0.545906,0.544655,-0.473804,-0.344258,-0.100205,-0.318173
32,1.635916,-0.969674,-0.333776,1.190588,-0.839044,-0.967709,-1.570006,0.608394,-1.005159,-0.447923,...,0.350831,0.272195,0.146327,0.466085,-0.545906,0.544655,-0.473804,0.383980,NaN,0.535870
33,NaN,0.645697,-0.414471,-0.556134,-0.747650,-1.230504,-0.196394,1.856670,-0.178405,-0.060418,...,-1.643365,0.272195,0.146327,-1.821968,-1.564930,1.468919,-0.473804,-1.800732,-1.617590,-0.318173
34,0.197294,1.186083,NaN,0.313932,1.043653,1.213022,-0.440000,0.533045,1.666543,0.824868,...,-0.646267,1.319101,-0.764152,-0.296600,-1.564930,-0.379608,1.421411,0.383980,-0.100205,0.535870
35,-0.000101,-0.482442,2.162513,NaN,-0.093111,0.846313,0.539765,-0.089866,-0.123881,-0.257936,...,2.345026,0.272195,1.056806,1.228769,0.473118,1.468919,-0.473804,1.112217,-0.858898,-0.318173
36,-0.776423,-0.359286,NaN,0.741847,-0.414889,0.338600,0.210264,2.258175,0.310448,-0.464801,...,-0.646267,1.319101,0.146327,-0.296600,0.473118,-0.379608,2.369018,0.383980,0.658488,-0.318173
37,0.877452,1.621582,0.933508,-0.508282,1.750293,0.881085,0.435576,NaN,0.425924,1.768278,...,-1.643365,1.319101,1.056806,1.991454,1.492143,1.468919,-0.473804,0.383980,-0.100205,0.535870
38,-0.383859,0.873595,-1.044075,-2.213227,-0.160971,0.940933,0.271911,0.231054,0.242020,-0.573757,...,0.350831,1.319101,-0.764152,1.228769,-1.564930,0.544655,1.421411,-1.800732,-0.100205,NaN
39,1.483917,2.659685,1.872958,NaN,0.131667,-0.049361,0.020624,-0.556146,1.509711,-0.016188,...,-0.646267,1.319101,-0.764152,1.228769,-0.545906,-1.303872,-1.421411,-1.072495,-0.100205,-0.318173
40,-0.331003,1.622384,-0.335772,-1.207513,0.739466,2.187573,1.548513,NaN,0.590160,-0.020242,...,-0.646267,0.272195,-0.764152,-0.296600,0.473118,0.544655,-0.473804,-0.344258,-0.858898,-0.318173
41,-2.079123,-0.637262,-1.674667,-0.385518,-1.157445,NaN,-0.795467,-1.933670,-0.765273,-0.279280,...,-0.646267,-1.821615,1.056806,-1.059284,-0.545906,0.544655,-0.473804,-0.344258,1.417181,-2.026258
42,1.249887,-0.680494,-0.877802,2.525612,0.871454,1.890201,1.107293,0.833341,-0.319971,1.693225,...,0.350831,1.319101,-0.764152,-1.059284,-1.564930,0.544655,-1.421411,NaN,-0.858898,-1.172215
43,-0.678982,-0.830199,-0.162714,0.575396,-0.974544,0.349766,-0.444508,1.359766,0.312715,0.324992,...,-0.646267,0.272195,-0.764152,-0.296600,1.492143,0.544655,NaN,-0.344258,0.658488,0.535870
44,-0.650443,-2.267784,-1.540249,-0.896617,-1.074183,-2.375658,-1.127259,-0.515257,-1.165329,-0.259937,...,1.347928,0.272195,1.056806,1.228769,0.473118,0.544655,0.473804,0.383980,NaN,-1.172215
45,1.950686,-0.508373,0.041859,NaN,-1.565072,0.626830,-0.165417,-0.794760,-1.507169,0.224664,...,0.350831,-0.774710,1.056806,-0.296600,-0.545906,-0.379608,-0.473804,-0.344258,-0.858898,1.389912
46,-1.596836,1.487729,0.221703,NaN,-1.515711,0.173718,-1.043757,-0.713170,-0.397802,-2.274267,...,-0.646267,-0.774710,1.056806,-0.296600,-2.583955,-1.303872,1.421411,0.383980,-0.100205,-0.318173
47,NaN,1.011594,0.822922,-0.104030,3.213354,0.012287,0.236638,0.158815,1.557840,-0.281674,...,-0.646267,-0.774710,0.146327,0.466085,0.473118,-0.379608,-0.473804,1.112217,0.658488,0.535870
48,-0.097760,-1.282748,-1.459878,-1.195237,-1.323885,-0.502974,-0.166793,-0.304563,-0.061251,1.241009,...,0.350831,0.272195,1.056806,0.466085,-1.564930,-0.379608,NaN,0.383980,-0.100205,-0.318173
49,-0.830656,-1.316867,-0.162792,0.504316,0.155374,0.867688,-0.022231,-0.512724,-0.311083,0.704147,...,1.347928,NaN,1.056806,-0.296600,0.473118,1.468919,-0.473804,0.383980,0.658488,1.389912
50,-0.003795,-1.393242,-0.127554,-0.536949,-0.339672,0.596129,-1.026451,0.058285,0.507789,-1.023344,...,0.350831,1.319101,1.056806,0.466085,0.473118,-0.379608,NaN,0.383980,-0.100205,0.535870
51,1.655310,0.599684,-0.326065,-0.618876,0.631529,0.567554,0.813020,0.959507,-0.003516,0.387890,...,0.350831,-0.774710,-0.764152,NaN,0.473118,-0.379608,0.473804,0.383980,-2.376283,-1.172215
52,-0.222170,1.056466,-1.222682,-1.193193,-1.582622,-0.338833,-0.036344,-0.904779,-1.634886,0.342316,...,0.350831,-0.774710,1.056806,0.466085,0.473118,-0.379608,NaN,1.112217,0.658488,-0.318173
53,-0.885025,-1.220796,1.717245,-1.040552,1.258976,0.592185,-0.642449,-0.208633,-0.467264,0.959333,...,0.350831,0.272195,1.056806,-0.296600,0.473118,-1.303872,-0.473804,-1.072495,-0.858898,NaN
54,0.276561,0.956659,0.288039,-0.453576,-0.383042,1.960815,1.090065,0.381890,1.189318,1.268374,...,-0.646267,-1.821615,0.146327,-0.296600,1.492143,0.544655,NaN,-0.344258,1.417181,1.389912
55,1.644654,1.362007,1.079798,1.053119,1.529444,NaN,0.362968,1.684148,1.439777,1.021093,...,-2.640463,-0.774710,-0.764152,-1.059284,-0.545906,-0.379608,-0.473804,-0.344258,-1.617590,0.535870

In [15]:
# change All the NaNs to 0
df = df.fillna(0)
# print(df)

In [16]:
# first row deleted from all the datasets to match the label DataFrame
df = df.drop(0)

otw_binding_df = otw_binding_df.drop(0)
print(otw_binding_df)
df

        ALA      ARG      ASN      ASP       CYS      GLU      GLN       GLY  \
1  -0.21010 -0.23700 -0.01127  0.11780  0.057450  0.10960      NaN -0.100400
2  -0.53270  0.42440  0.15390  3.19700 -0.145800  2.56400  0.24390  0.391100
3   0.28620  0.06292  0.31290  0.27870  0.275200  0.29270  0.13690  0.428100
4   0.40510  1.53900 -0.67030  3.64600  0.232300  1.79300  0.48630  0.760900
5   0.32910  0.05287  0.21950  0.32450  0.226100  0.01604  0.03691 -0.071460
6   0.09246  1.17600  0.93350  1.92200  0.005105  1.01800  1.02400  0.800300
7   0.09121 -0.16120      NaN  0.14160  0.031480  0.14990  0.02013  0.186800
8   0.16420  0.81170  1.31000  1.22600  0.294900  1.28700  1.19600       NaN
9   0.13870 -0.23390 -0.01097  0.13930  0.096320  0.20320  0.12390  0.381800
10  0.66110  0.55590  0.56760  0.71900  0.603700  0.73670  0.64630  0.803300
11  1.07500  1.00100  1.22500  1.24200  0.739500  1.12500  0.97690  1.003000
12  0.11880 -0.11940  0.02339  0.46300  0.013320  0.22100  0.12460  0.282700
13  0.92680  1.06500  1.00700  1.22000  0.933100  0.84250  1.02800       NaN
14  0.14470 -0.15760  0.20610  0.36990 -0.057740      NaN -0.12900  0.545200
15  0.52600 -0.02494  0.48440  0.93680  0.410400  0.46670  0.28840  0.464600
16 -0.07117 -0.15540  0.23110  0.54950  0.003414  0.25150  0.03647 -0.324300
17  0.01916 -0.13240  0.22850  0.90390 -0.028370  0.92450  0.31770  0.360400
18 -0.18900 -0.28520 -0.19990 -0.01905 -0.175300      NaN -0.19160 -0.173200
19      NaN -0.69840  0.24360  0.95400  0.185400  0.73480  0.19290  0.177900
20  0.13500 -0.26710  0.03803  0.32890  0.009592  0.43090  0.10820  0.028740
21 -0.33380 -0.09322 -0.06135      NaN -0.250100 -0.29040 -0.30000 -0.198000
22      NaN  1.97300  0.56050  0.72560  0.877400  1.01900  1.74400  0.611300
23      NaN  0.64900 -0.77690 -0.03150 -0.668300 -1.31400 -0.91260 -0.760000
24 -0.01572 -0.76520  0.12360  0.75660 -0.206600  0.79620 -0.31470  0.142700
25      NaN  3.17900  1.91900  3.07900  0.242600  3.00200  0.71650 -0.043800
26  8.88200  8.88200  8.88200  5.31500  3.891000      NaN  8.88200  8.882000
27  1.95600  0.70220  2.11500  3.94100  1.402000  3.63400  1.98200  1.954000
28 -0.14650 -0.93020 -0.19850  0.98660 -0.149600  0.91290 -0.17180  0.059990
29  1.04100  4.13500  0.34850  4.02600  0.397900  1.62900  0.65590  1.286000
30  8.34700  1.09600  4.70800  8.88200  3.671000  8.88200  8.15100  8.882000
31  0.27620 -0.18850 -0.34580  1.91100  0.266400  1.83000      NaN -0.206900
32  1.06200  0.76750  1.02500  2.01300  0.797900  1.81800  0.90160  0.575100
33      NaN  3.13700  3.48500  4.79000  0.040060  5.38100  3.80900  1.033000
34  2.99700  3.00600      NaN  3.58900  2.023000  3.50500  3.27600  2.004000
35 -0.31810 -0.39210 -0.45080      NaN -0.266700 -0.03653 -0.17200 -0.379400
36  1.04900  1.07900      NaN  1.79200  0.483400  1.22100  0.87530  0.730300
37  0.07992  0.59530  0.53490  0.46620  0.468800  0.57120  0.57270       NaN
38  1.95400  0.76850  2.88600  3.49100  1.112000  1.96000  1.61000  3.356000
39 -0.61190 -0.27820 -0.29370      NaN -0.461800  0.28930  0.06726  0.275500
40  1.60100  5.42300  4.09800  3.54500  2.031000  3.65800  4.95800       NaN
41 -0.21320 -0.40980 -0.25220 -0.02147 -0.245000      NaN -0.52760 -0.237200
42  5.74100  4.25300  8.88200  8.88200  4.025000  8.88200  8.88200  4.463000
43 -0.20880 -0.03776  0.24950  0.39070  0.143500  0.12510 -0.19160 -0.176800
44  2.00200  2.04600  2.15700  3.46100  1.175000  3.28800  2.50000  2.290000
45 -0.06443 -0.14510 -0.14560      NaN -0.109200  0.10100 -0.06850 -0.057950
46 -0.34230 -0.88140 -0.31790      NaN -0.208500  0.01884 -0.35810 -0.273100
47      NaN -0.12630 -0.06917  0.02936 -0.054150 -0.01043 -0.10450 -0.060910
48 -0.03279 -0.11560 -0.01311  0.04634 -0.081670 -0.01387 -0.07136 -0.021820
49 -0.02716 -0.11770  0.10980  0.10920  0.122300  0.05539  0.05377 -0.257800
50  0.21610 -0.33920 -0.20650 -0.17180 -0.029020 -0.23950 -0.30970  0.001576
51  2.64100  4.70300  3.94900  4.99300  2.560000  3.57100  3.87000  4.254000
52  0.06596  0.15360  0.26980  0.37690  0.124300  0.10550  0.06989 -0.444400
53 -0.15610  3.92500  1.03000  1.87900 -0.175100  2.17400  1.47600 -3.698000
54  0.36540  0.15660  0.43130  0.57770  0.349000  0.44870  0.37250  0.629500
55  0.82080  0.88720  1.07200  1.15400  1.060000      NaN  0.67300  0.979400

        HIS       ILE       LEU      LYS      MET      PHE      PRO       SER  \
1  -0.06150 -0.060400 -0.125500 -0.13380 -0.16610 -0.25560 -0.17520 -0.096860
2  -0.03647  0.890900  0.221100  0.52040  0.38220  0.06194 -0.04813 -0.307400
3   0.25470  0.094770 -0.139800      NaN  0.09856  0.25520  0.64380  0.262500
4   0.56000  1.090000       NaN  1.14900  0.72830  0.55370  3.67000 -0.021190
5   0.03814       NaN -0.132900  0.06214  0.23690 -0.07075  1.76400  0.281800
6   1.67400 -0.327600       NaN  0.71690  0.60610  0.76100  0.29990  0.321000
7  -0.09388  0.171600  0.120800 -0.08819  0.28750 -0.25810  2.19700  0.145300
8   0.98700  1.167000  0.975000  1.19500  1.20400  0.86900  0.83250  0.580600
9   0.03444  0.057260  0.065260      NaN  0.31380  0.13540  0.58000  0.178100
10  0.61700  0.634800  0.643000  0.57020  0.86450  0.61170  1.06400  0.270600
11  1.10900  0.585100       NaN  1.01100  0.86610  0.71720  1.39800  1.082000
12  0.24530  0.185300  0.408000      NaN  0.19960  0.22860  1.07800 -0.205200
13  1.05300  1.041000  1.263000  1.23200  1.56000  1.31000  1.47800  0.990800
14 -0.28930 -0.137100  0.134400  0.02707  0.22910 -0.04606  0.99110 -0.171300
15  0.41670  0.138100  0.211500  0.08608  0.45600  0.62110  0.57620  0.420100
16 -0.12810  0.252900  0.171600  0.04606  0.13860 -0.02430  0.67940 -0.009727
17  0.05118  0.192400  0.421800 -0.05714  0.75310  0.16040  1.70300  0.124700
18 -0.21200 -0.243700 -0.219300 -0.25440 -0.03044 -0.24580 -0.21920 -0.161700
19  0.41260  0.805300  0.689100 -0.33680  0.52360  1.01100  0.75460  0.018620
20  0.03468 -0.002215  0.071280  0.11140  0.27960 -0.13540  0.15630  0.099180
21 -0.20920 -0.201300 -0.241200  0.06905 -0.05176 -0.23010 -0.05040 -0.067950
22  1.86200  1.711000  1.724000  1.88200  2.30900  3.45200  0.02766  0.231100
23 -1.44500 -0.211600 -0.128000  1.35800 -0.62500 -1.40100 -1.26000 -0.572800
24 -0.20630 -0.232700  0.000775 -0.07941 -0.55490 -0.40160 -0.07980 -0.221200
25  1.40200  1.265000  2.917000  3.04700  1.17800  1.85800  0.70300  0.041440
26  8.88200  8.882000  8.882000  8.88200  8.88200  8.88200  5.68000  8.882000
27  1.60200  0.928900  1.166000      NaN  1.42200  1.38700  1.76500  2.130000
28 -0.07707 -0.115900 -0.117000 -0.70460 -0.07259  0.03295  1.52600 -0.129100
29  0.13720  1.132000  0.302500  0.18820  0.41000      NaN  3.85500  0.439000
30  8.88200  4.622000  3.721000      NaN  3.18000  8.88200  4.21800  8.882000
31 -0.05057  0.748200  0.112400 -0.13370  0.23030  1.01800  2.73700  0.182700
32  0.68350  1.062000  0.333200  0.73820  0.55620 -0.25270  3.68200  1.044000
33  4.24000  2.015000  2.040000  6.27900  0.33590  2.92500  4.78700  0.268100
34  2.81200  2.337000  3.050000  3.66100  2.92000  2.61700  8.78600  2.009000
35 -0.02769 -0.182500 -0.239300 -0.18320 -0.23340  0.13920  2.90300 -0.330300
36  0.75670  0.641100  0.788900  0.99820  1.00100  1.78200  3.82700  0.425500
37  0.57030  1.025000  0.380100  0.59160  0.58040  0.45560  1.56300  0.415200
38  1.97700 -0.072890 -0.168900  0.79690  0.12370  0.81440  3.44400  2.207000
39 -0.90270 -0.322000  0.242100  0.04918  0.07682 -0.93790  0.78750 -0.499900
40  4.78300  8.827000  3.167000  5.19400  3.07000  1.86400  4.46900  3.159000
41 -0.07744 -0.430300 -0.540200 -0.29070 -0.33970 -0.24000  0.38030 -0.305300
42  4.18800  7.853000  4.331000  8.88200  8.88200  2.97900  8.88200  5.236000
43 -0.00135  0.512100  0.083580 -0.05180 -0.01732  0.09319  3.93400 -0.019220
44  1.04300  1.021000  0.593000  2.13900  0.91870  0.16080  3.93300  2.159000
45 -0.06966 -0.040530 -0.062480 -0.12550 -0.03503  0.04774  2.18600 -0.148000
46 -0.57880 -0.193500 -0.253200 -0.56710 -0.18680 -0.39970 -0.41080 -0.383300
47 -0.11290 -0.135700 -0.116600 -0.12720 -0.09726 -0.14540 -0.08263 -0.077150
48 -0.06578 -0.183900 -0.086970 -0.11640 -0.04210 -0.04496  0.07254 -0.110300
49 -0.02425  0.179500  0.176600      NaN  0.25040  0.29970  0.69510  0.012670
50 -0.33180 -0.337600 -0.517300 -0.35630 -0.39110 -0.29580  3.03100  0.189700
51  2.61500  1.843000  1.072000  4.34700  1.19200      NaN  4.39500  3.694000
52  0.38170  0.273000  0.491700  0.13180  0.24260  0.51390  3.68000 -0.018260
53  1.36200  0.885800  0.802600  3.59600  0.46680  0.28690  3.60500  0.558300
54  0.47670  0.525700  0.478100  0.21810  0.43610  0.44950  2.23100  0.237100
55  0.97270  1.233000  1.232000  0.94170  1.13500  1.03800  1.22600  0.763500

        THR       TRP      TYR      VAL
1  -0.12380 -0.164500 -0.14230 -0.01975
2  -0.27400  0.017310      NaN  0.72750
3   0.19110  0.143200  0.25220  0.08689
4  -0.16240  1.904000  1.49900  0.28370
5   0.04241 -0.042740 -0.15640  0.11190
6   0.16620  1.473000  1.24900 -0.11950
7   0.35340 -0.065840 -0.28520  0.18390
8   0.76950  0.803000  0.83350  1.11100
9   0.05992  0.036200  0.08135  0.03159
10      NaN  0.578200  0.55650  0.59920
11  0.98800  1.057000  1.27600  0.72320
12 -0.29260 -0.273900  0.40450  0.08319
13  0.93490  0.713000  1.16100  0.91690
14 -0.18420 -0.165000 -0.27100 -0.17480
15      NaN  0.766400  0.62510  0.17160
16      NaN -0.163100 -0.02668  0.21510
17      NaN  0.081880  0.12390  0.01081
18 -0.17070 -0.249000 -0.23130 -0.24040
19  0.02184  0.733800  0.83500  0.07236
20  0.12310 -0.201500 -0.15670      NaN
21 -0.17560 -0.358200 -0.23660 -0.27610
22  0.83850  3.962000  3.64800  1.02500
23 -0.75660 -1.612000 -2.13600 -0.30710
24      NaN -0.592000 -0.02714  0.14480
25  0.37390  0.746200  1.13600  0.79750
26  8.88200  8.882000  8.88200  8.88200
27  1.63200  2.145000  2.11900  1.19500
28 -0.10520  0.236200  0.01036      NaN
29  1.28500  0.544600  0.55790  0.68950
30  8.88200  4.227000  8.88200  8.88200
31  0.41450  0.980500  1.06000  0.72360
32  1.16400  0.381800      NaN  1.24000
33  1.21200  3.314000  2.37700  1.24200
34  1.56000  2.338000  2.80800  3.22000
35 -0.23760  0.166700  0.05209 -0.33610
36  0.59820  1.175000  1.48800  0.88980
37  0.54650  0.357500  0.37210  0.64330
38  1.06300  2.866000  1.68500      NaN
39  0.04238 -1.320000 -1.25800 -0.42450
40  5.32600  3.573000  2.90400  3.00800
41 -0.38300 -0.478600 -0.22890 -0.37780
42  5.07500       NaN  3.45400  6.22100
43      NaN -0.062060  0.20220  0.62050
44  2.21100 -0.420400      NaN  1.37400
45 -0.24160  0.004863  0.10360 -0.09134
46 -0.24080 -0.571400 -0.35600 -0.25480
47 -0.09280 -0.115100 -0.11290 -0.12360
48      NaN -0.113600 -0.08481 -0.01559
49  0.07026  0.122300  0.22130  0.03301
50      NaN -0.363700 -0.32700 -0.35970
51  3.31600  3.564000  1.61800  2.22900
52      NaN  0.089110  0.46170  0.05215
53  0.47510  0.481500  2.35100      NaN
54      NaN  0.269900  0.38040  0.38560
55  0.67780  0.808100  1.09400  0.93100

,0,1,2,3,4,5,6,7,8,9,...,10,11,12,13,14,15,16,17,18,19
1,-0.491258,-0.257499,-1.052298,-0.584169,0.704927,-1.329820,-0.829858,-1.624188,-0.864299,1.250216,...,-0.646267,0.272195,-0.764152,-0.296600,0.473118,-1.303872,0.000000,0.383980,-0.100205,1.389912
2,1.396358,1.711676,1.742959,1.133086,0.718241,-0.035871,3.937579,0.336038,-1.415303,1.210541,...,1.347928,-1.821615,0.146327,0.466085,-0.545906,0.544655,0.473804,-0.344258,0.000000,-0.318173
3,-0.802705,-0.513096,0.885495,0.810723,-0.630501,-1.437084,-1.190185,2.178055,-1.236438,1.956218,...,0.350831,0.000000,1.967285,-0.296600,-0.545906,-1.303872,0.473804,-0.344258,-0.100205,1.389912
4,-1.543321,-0.652125,0.102321,0.204055,1.416039,0.121732,-0.493913,0.548179,0.446072,0.094693,...,0.000000,-1.821615,-1.674631,1.228769,0.473118,-0.379608,0.473804,1.112217,-0.100205,-1.172215
5,-0.337005,-0.256630,-0.602955,1.408445,0.605510,0.002404,-0.023203,-0.158317,-0.349300,0.000000,...,0.350831,-0.774710,0.146327,-0.296600,1.492143,-2.228135,0.473804,0.383980,-0.100205,0.000000
6,1.357916,-0.149534,1.730235,-1.101519,-0.198366,-1.135083,1.937820,0.152036,1.580575,1.549609,...,1.347928,-1.821615,0.146327,1.228769,0.473118,0.544655,-0.473804,-0.344258,0.658488,1.389912
7,-0.222113,0.518603,0.000000,-0.754566,-1.504821,0.354036,0.045325,-0.065599,0.848171,-1.320680,...,0.350831,-0.774710,0.146327,-0.296600,-0.545906,-0.379608,0.473804,0.383980,-0.858898,-0.318173
8,-0.940664,-0.238521,-1.085072,0.561585,-0.487877,-1.201839,-0.721859,0.000000,0.802801,0.578210,...,-0.646267,0.272195,0.146327,-1.059284,-0.545906,1.468919,1.421411,-1.800732,-0.858898,-0.318173
9,-1.315341,0.124813,1.157802,0.201989,-0.793833,0.196504,-0.027478,-0.229627,0.093073,-0.405633,...,0.350831,0.000000,-0.764152,1.991454,0.473118,-1.303872,-1.421411,0.383980,-0.100205,0.535870
10,-1.304603,-0.368128,-0.192787,0.319075,0.664042,-0.933641,-1.542970,-1.785182,1.296694,-0.605873,...,-0.646267,0.272195,0.146327,0.466085,0.473118,0.544655,0.000000,-0.344258,-0.100205,0.535870
11,1.394942,-0.816397,-0.585574,0.723024,-0.148306,-0.654033,-0.314275,0.935780,-0.587794,-0.885065,...,0.000000,-0.774710,1.056806,-1.059284,0.473118,1.468919,-1.421411,1.112217,-0.858898,0.535870
12,-1.340255,0.785255,-0.849094,-0.844330,0.518924,0.908376,0.556960,-0.379146,0.993703,-1.593892,...,-0.646267,0.000000,0.146327,-1.059284,1.492143,0.544655,-0.473804,1.112217,0.658488,0.535870
13,-0.578040,0.567615,-0.490451,0.209451,2.292721,-0.655960,-0.773135,0.000000,0.282838,-1.964847,...,1.347928,2.366006,0.146327,-1.059284,2.511167,1.468919,-0.473804,0.383980,-0.100205,0.535870
14,0.007678,-1.117396,1.648216,0.621574,-1.205436,0.000000,0.545355,-0.010766,-0.859234,-0.614711,...,0.350831,0.272195,-0.764152,-0.296600,-0.545906,-1.303872,1.421411,0.383980,0.658488,0.535870
15,1.268347,-0.261783,0.484316,-1.925605,-0.858323,0.583387,-0.152550,0.793847,-2.061504,0.267530,...,0.350831,0.272195,0.146327,0.466085,-0.545906,-0.379608,0.000000,1.112217,2.175874,0.535870
16,-1.254935,-0.543043,-1.089885,-0.697275,0.088184,-0.568383,-0.753114,-2.531899,-2.189604,0.487385,...,-1.643365,0.272195,1.056806,1.991454,-0.545906,0.544655,0.000000,0.383980,1.417181,-0.318173
17,1.035517,-1.361032,0.868618,-1.133410,0.480359,1.820882,0.589999,0.921246,-0.856853,0.972458,...,1.347928,0.272195,-0.764152,-0.296600,0.473118,-0.379608,0.000000,0.383980,0.658488,1.389912
18,-0.906106,0.603072,-0.835339,0.291817,-0.113593,0.000000,-0.722509,-0.607474,-0.261468,0.211960,...,0.350831,0.272195,-0.764152,0.466085,0.473118,-1.303872,-0.473804,0.383980,0.658488,-1.172215
19,0.000000,0.229514,0.174441,-0.895057,-0.572567,0.216790,-0.278941,0.467371,0.287324,-0.640028,...,0.350831,-0.774710,0.146327,0.466085,-0.545906,0.544655,-0.473804,1.840454,-1.617590,1.389912
20,0.266079,-0.004072,-1.527163,2.064288,-0.803853,0.387914,-0.294617,-0.524502,-0.718456,-0.620137,...,1.347928,0.272195,1.056806,0.466085,-1.564930,0.544655,0.473804,-0.344258,-0.100205,0.000000
21,0.685896,1.301175,-0.058878,0.000000,-0.121732,-0.926594,-0.508279,-1.093365,-1.457920,-0.156698,...,-0.646267,-0.774710,-1.674631,-1.059284,0.473118,-0.379608,0.473804,-1.072495,0.658488,0.535870
22,0.000000,-1.167089,0.611357,1.338756,1.559174,-0.486269,1.059011,-1.248401,-0.410483,0.763128,...,0.350831,1.319101,0.146327,-0.296600,0.473118,-0.379608,-0.473804,-1.800732,2.175874,0.535870
23,0.000000,0.754031,0.546774,1.106245,0.515040,1.692179,-0.008674,0.057863,0.897320,0.308676,...,-1.643365,-1.821615,0.146327,0.466085,1.492143,0.544655,-0.473804,0.383980,0.658488,-0.318173
24,-0.577558,-1.203535,-1.094175,0.603953,-1.124069,-1.533990,-1.346107,-1.161081,1.437624,-1.933780,...,0.350831,-0.774710,-0.764152,-0.296600,-0.545906,0.544655,0.000000,1.840454,0.658488,0.535870
25,0.000000,0.349524,1.875926,-0.036132,0.760477,-1.136917,2.164455,-0.077650,2.028902,0.322476,...,0.350831,0.272195,-0.764152,-1.821968,0.473118,-0.379608,-0.473804,0.383980,0.658488,-2.026258
26,-0.295670,0.708699,-0.249985,0.214721,-0.063649,0.000000,0.955263,-0.662680,0.972722,-0.044229,...,-1.643365,0.272195,-2.585110,-0.296600,-0.545906,-2.228135,-2.369018,-1.800732,-0.100205,-2.880300
27,-0.466618,0.500255,0.030545,0.744398,-0.101243,0.238547,0.920639,1.377874,-0.234796,0.439369,...,-0.646267,0.000000,-0.764152,-0.296600,-0.545906,1.468919,2.369018,-1.072495,1.417181,-2.026258
28,0.541010,0.310297,0.129858,0.488587,0.118491,-0.111118,0.550194,0.944805,0.148483,-0.371745,...,0.350831,0.272195,1.056806,0.466085,-0.545906,0.544655,0.473804,1.840454,-0.100205,0.000000
29,0.269008,-1.028131,0.118411,-0.588671,0.218361,-1.197105,0.473266,-0.421661,1.202275,-1.369544,...,0.350831,0.272195,0.146327,0.000000,1.492143,-0.379608,1.421411,-0.344258,-0.100205,-0.318173
30,0.753253,-0.981611,0.211373,0.845540,-0.558372,-0.293479,-1.497060,0.642715,-0.487453,0.544037,...,-1.643365,0.000000,-3.495588,-3.347337,-1.564930,-2.228135,-0.473804,-3.257207,-3.134976,-1.172215
31,0.523306,0.156450,-0.951190,0.593924,0.078088,-0.346812,0.000000,-0.828963,-0.372517,-2.400583,...,1.347928,1.319101,0.146327,0.466085,-0.545906,0.544655,-0.473804,-0.344258,-0.100205,-0.318173
32,1.635916,-0.969674,-0.333776,1.190588,-0.839044,-0.967709,-1.570006,0.608394,-1.005159,-0.447923,...,0.350831,0.272195,0.146327,0.466085,-0.545906,0.544655,-0.473804,0.383980,0.000000,0.535870
33,0.000000,0.645697,-0.414471,-0.556134,-0.747650,-1.230504,-0.196394,1.856670,-0.178405,-0.060418,...,-1.643365,0.272195,0.146327,-1.821968,-1.564930,1.468919,-0.473804,-1.800732,-1.617590,-0.318173
34,0.197294,1.186083,0.000000,0.313932,1.043653,1.213022,-0.440000,0.533045,1.666543,0.824868,...,-0.646267,1.319101,-0.764152,-0.296600,-1.564930,-0.379608,1.421411,0.383980,-0.100205,0.535870
35,-0.000101,-0.482442,2.162513,0.000000,-0.093111,0.846313,0.539765,-0.089866,-0.123881,-0.257936,...,2.345026,0.272195,1.056806,1.228769,0.473118,1.468919,-0.473804,1.112217,-0.858898,-0.318173
36,-0.776423,-0.359286,0.000000,0.741847,-0.414889,0.338600,0.210264,2.258175,0.310448,-0.464801,...,-0.646267,1.319101,0.146327,-0.296600,0.473118,-0.379608,2.369018,0.383980,0.658488,-0.318173
37,0.877452,1.621582,0.933508,-0.508282,1.750293,0.881085,0.435576,0.000000,0.425924,1.768278,...,-1.643365,1.319101,1.056806,1.991454,1.492143,1.468919,-0.473804,0.383980,-0.100205,0.535870
38,-0.383859,0.873595,-1.044075,-2.213227,-0.160971,0.940933,0.271911,0.231054,0.242020,-0.573757,...,0.350831,1.319101,-0.764152,1.228769,-1.564930,0.544655,1.421411,-1.800732,-0.100205,0.000000
39,1.483917,2.659685,1.872958,0.000000,0.131667,-0.049361,0.020624,-0.556146,1.509711,-0.016188,...,-0.646267,1.319101,-0.764152,1.228769,-0.545906,-1.303872,-1.421411,-1.072495,-0.100205,-0.318173
40,-0.331003,1.622384,-0.335772,-1.207513,0.739466,2.187573,1.548513,0.000000,0.590160,-0.020242,...,-0.646267,0.272195,-0.764152,-0.296600,0.473118,0.544655,-0.473804,-0.344258,-0.858898,-0.318173
41,-2.079123,-0.637262,-1.674667,-0.385518,-1.157445,0.000000,-0.795467,-1.933670,-0.765273,-0.279280,...,-0.646267,-1.821615,1.056806,-1.059284,-0.545906,0.544655,-0.473804,-0.344258,1.417181,-2.026258
42,1.249887,-0.680494,-0.877802,2.525612,0.871454,1.890201,1.107293,0.833341,-0.319971,1.693225,...,0.350831,1.319101,-0.764152,-1.059284,-1.564930,0.544655,-1.421411,0.000000,-0.858898,-1.172215
43,-0.678982,-0.830199,-0.162714,0.575396,-0.974544,0.349766,-0.444508,1.359766,0.312715,0.324992,...,-0.646267,0.272195,-0.764152,-0.296600,1.492143,0.544655,0.000000,-0.344258,0.658488,0.535870
44,-0.650443,-2.267784,-1.540249,-0.896617,-1.074183,-2.375658,-1.127259,-0.515257,-1.165329,-0.259937,...,1.347928,0.272195,1.056806,1.228769,0.473118,0.544655,0.473804,0.383980,0.000000,-1.172215
45,1.950686,-0.508373,0.041859,0.000000,-1.565072,0.626830,-0.165417,-0.794760,-1.507169,0.224664,...,0.350831,-0.774710,1.056806,-0.296600,-0.545906,-0.379608,-0.473804,-0.344258,-0.858898,1.389912
46,-1.596836,1.487729,0.221703,0.000000,-1.515711,0.173718,-1.043757,-0.713170,-0.397802,-2.274267,...,-0.646267,-0.774710,1.056806,-0.296600,-2.583955,-1.303872,1.421411,0.383980,-0.100205,-0.318173
47,0.000000,1.011594,0.822922,-0.104030,3.213354,0.012287,0.236638,0.158815,1.557840,-0.281674,...,-0.646267,-0.774710,0.146327,0.466085,0.473118,-0.379608,-0.473804,1.112217,0.658488,0.535870
48,-0.097760,-1.282748,-1.459878,-1.195237,-1.323885,-0.502974,-0.166793,-0.304563,-0.061251,1.241009,...,0.350831,0.272195,1.056806,0.466085,-1.564930,-0.379608,0.000000,0.383980,-0.100205,-0.318173
49,-0.830656,-1.316867,-0.162792,0.504316,0.155374,0.867688,-0.022231,-0.512724,-0.311083,0.704147,...,1.347928,0.000000,1.056806,-0.296600,0.473118,1.468919,-0.473804,0.383980,0.658488,1.389912
50,-0.003795,-1.393242,-0.127554,-0.536949,-0.339672,0.596129,-1.026451,0.058285,0.507789,-1.023344,...,0.350831,1.319101,1.056806,0.466085,0.473118,-0.379608,0.000000,0.383980,-0.100205,0.535870
51,1.655310,0.599684,-0.326065,-0.618876,0.631529,0.567554,0.813020,0.959507,-0.003516,0.387890,...,0.350831,-0.774710,-0.764152,0.000000,0.473118,-0.379608,0.473804,0.383980,-2.376283,-1.172215
52,-0.222170,1.056466,-1.222682,-1.193193,-1.582622,-0.338833,-0.036344,-0.904779,-1.634886,0.342316,...,0.350831,-0.774710,1.056806,0.466085,0.473118,-0.379608,0.000000,1.112217,0.658488,-0.318173
53,-0.885025,-1.220796,1.717245,-1.040552,1.258976,0.592185,-0.642449,-0.208633,-0.467264,0.959333,...,0.350831,0.272195,1.056806,-0.296600,0.473118,-1.303872,-0.473804,-1.072495,-0.858898,0.000000
54,0.276561,0.956659,0.288039,-0.453576,-0.383042,1.960815,1.090065,0.381890,1.189318,1.268374,...,-0.646267,-1.821615,0.146327,-0.296600,1.492143,0.544655,0.000000,-0.344258,1.417181,1.389912
55,1.644654,1.362007,1.079798,1.053119,1.529444,0.000000,0.362968,1.684148,1.439777,1.021093,...,-2.640463,-0.774710,-0.764152,-1.059284,-0.545906,-0.379608,-0.473804,-0.344258,-1.617590,0.535870

In [17]:
column_names = ['ALA_sasa_ub', 'ARG_sasa_ub', 'ASN_sasa_ub', 'ASP_sasa_ub', 'CYS_sasa_ub', 'GLU_sasa_ub', 'GLN_sasa_ub', 'GLY_sasa_ub', 'HIS_sasa_ub', 'ILE_sasa_ub', 'LEU_sasa_ub', 'LYS_sasa_ub', 'MET_sasa_ub', 'PHE_sasa_ub', 'PRO_sasa_ub', 'SER_sasa_ub', 'THR_sasa_ub', 'TRP_sasa_ub', 'TYR_sasa_ub', 'VAL_sasa_ub',
                'ALA_sasa_bnd', 'ARG_sasa_bnd', 'ASN_sasa_bnd', 'ASP_sasa_bnd', 'CYS_sasa_bnd', 'GLU_sasa_bnd', 'GLN_sasa_bnd', 'GLY_sasa_bnd', 'HIS_sasa_bnd', 'ILE_sasa_bnd', 'LEU_sasa_bnd', 'LYS_sasa_bnd', 'MET_sasa_bnd', 'PHE_sasa_bnd', 'PRO_sasa_bnd', 'SER_sasa_bnd', 'THR_sasa_bnd', 'TRP_sasa_bnd', 'TYR_sasa_bnd', 'VAL_sasa_bnd',
                'ALA_sasa_wh', 'ARG_sasa_wh', 'ASN_sasa_wh', 'ASP_sasa_wh', 'CYS_sasa_wh', 'GLU_sasa_wh', 'GLN_sasa_wh', 'GLY_sasa_wh', 'HIS_sasa_wh', 'ILE_sasa_wh', 'LEU_sasa_wh', 'LYS_sasa_wh', 'MET_sasa_wh', 'PHE_sasa_wh', 'PRO_sasa_wh', 'SER_sasa_wh', 'THR_sasa_wh', 'TRP_sasa_wh', 'TYR_sasa_wh', 'VAL_sasa_wh',
                'ALA_sasa_fcc', 'ARG_sasa_fcc', 'ASN_sasa_fcc', 'ASP_sasa_fcc', 'CYS_sasa_fcc', 'GLU_sasa_fcc', 'GLN_sasa_fcc', 'GLY_sasa_fcc', 'HIS_sasa_fcc', 'ILE_sasa_fcc', 'LEU_sasa_fcc', 'LYS_sasa_fcc', 'MET_sasa_fcc', 'PHE_sasa_fcc', 'PRO_sasa_fcc', 'SER_sasa_fcc', 'THR_sasa_fcc', 'TRP_sasa_fcc', 'TYR_sasa_fcc', 'VAL_sasa_fcc',
                'ALA_hbnd', 'ARG_hbnd', 'ASN_hbnd', 'ASP_hbnd', 'CYS_hbnd', 'GLU_hbnd', 'GLN_hbnd', 'GLY_hbnd', 'HIS_hbnd', 'ILE_hbnd', 'LEU_hbnd', 'LYS_hbnd', 'MET_hbnd', 'PHE_hbnd', 'PRO_hbnd', 'SER_hbnd', 'THR_hbnd', 'TRP_hbnd', 'TYR_hbnd', 'VAL_hbnd'
               ]

In [18]:
# Check the number of names matches the number of columns
assert len(column_names) == df.shape[1], "Number of names doesn't match the number of columns"

# Assign new column names to the DataFrame
df.columns = column_names

In [19]:
df.head()

,ALA_sasa_ub,ARG_sasa_ub,ASN_sasa_ub,ASP_sasa_ub,CYS_sasa_ub,GLU_sasa_ub,GLN_sasa_ub,GLY_sasa_ub,HIS_sasa_ub,ILE_sasa_ub,...,LEU_hbnd,LYS_hbnd,MET_hbnd,PHE_hbnd,PRO_hbnd,SER_hbnd,THR_hbnd,TRP_hbnd,TYR_hbnd,VAL_hbnd
1,-0.491258,-0.257499,-1.052298,-0.584169,0.704927,-1.329820,-0.829858,-1.624188,-0.864299,1.250216,...,-0.646267,0.272195,-0.764152,-0.296600,0.473118,-1.303872,0.000000,0.383980,-0.100205,1.389912
2,1.396358,1.711676,1.742959,1.133086,0.718241,-0.035871,3.937579,0.336038,-1.415303,1.210541,...,1.347928,-1.821615,0.146327,0.466085,-0.545906,0.544655,0.473804,-0.344258,0.000000,-0.318173
3,-0.802705,-0.513096,0.885495,0.810723,-0.630501,-1.437084,-1.190185,2.178055,-1.236438,1.956218,...,0.350831,0.000000,1.967285,-0.296600,-0.545906,-1.303872,0.473804,-0.344258,-0.100205,1.389912
4,-1.543321,-0.652125,0.102321,0.204055,1.416039,0.121732,-0.493913,0.548179,0.446072,0.094693,...,0.000000,-1.821615,-1.674631,1.228769,0.473118,-0.379608,0.473804,1.112217,-0.100205,-1.172215
5,-0.337005,-0.256630,-0.602955,1.408445,0.605510,0.002404,-0.023203,-0.158317,-0.349300,0.000000,...,0.350831,-0.774710,0.146327,-0.296600,1.492143,-2.228135,0.473804,0.383980,-0.100205,0.000000

In [20]:
# Define the number of columns in each set (20)
columns_per_feature = hbnd_df.shape[1]

# Calculate the number of sets
num_sets = df.shape[1] // columns_per_feature

In [21]:
otw_binding_df = otw_binding_df.fillna(0)
otw_binding_df.head()

,ALA,ARG,ASN,ASP,CYS,GLU,GLN,GLY,HIS,ILE,LEU,LYS,MET,PHE,PRO,SER,THR,TRP,TYR,VAL
1,-0.2101,-0.23700,-0.01127,0.1178,0.05745,0.10960,0.00000,-0.10040,-0.06150,-0.06040,-0.1255,-0.13380,-0.16610,-0.25560,-0.17520,-0.09686,-0.12380,-0.16450,-0.1423,-0.01975
2,-0.5327,0.42440,0.15390,3.1970,-0.14580,2.56400,0.24390,0.39110,-0.03647,0.89090,0.2211,0.52040,0.38220,0.06194,-0.04813,-0.30740,-0.27400,0.01731,0.0000,0.72750
3,0.2862,0.06292,0.31290,0.2787,0.27520,0.29270,0.13690,0.42810,0.25470,0.09477,-0.1398,0.00000,0.09856,0.25520,0.64380,0.26250,0.19110,0.14320,0.2522,0.08689
4,0.4051,1.53900,-0.67030,3.6460,0.23230,1.79300,0.48630,0.76090,0.56000,1.09000,0.0000,1.14900,0.72830,0.55370,3.67000,-0.02119,-0.16240,1.90400,1.4990,0.28370
5,0.3291,0.05287,0.21950,0.3245,0.22610,0.01604,0.03691,-0.07146,0.03814,0.00000,-0.1329,0.06214,0.23690,-0.07075,1.76400,0.28180,0.04241,-0.04274,-0.1564,0.11190

In [22]:
Totw_binding_df = (otw_binding_df.T).set_index([np.arange(0,20)])

In [23]:
sasa_delta_df = sasa_ub_df - sasa_bnd_df
sasa_delta_df.head(5)

,ALA,ARG,ASN,ASP,CYS,GLU,GLN,GLY,HIS,ILE,LEU,LYS,MET,PHE,PRO,SER,THR,TRP,TYR,VAL
0,780.926270,619.477539,635.413818,578.694580,573.823486,528.156250,498.638916,634.449219,548.219726,567.938720,542.287110,606.787110,NaN,546.930908,590.053711,583.168213,NaN,630.234375,580.586182,521.445557
1,514.036866,536.218261,524.572754,627.192383,688.999756,479.757569,574.373047,485.742920,534.735596,660.983398,449.875244,414.875732,536.951905,543.414551,393.100342,518.388916,NaN,588.469727,446.447998,670.922363
2,765.574951,795.186279,701.497314,581.229492,551.749756,629.768311,829.531006,497.844238,466.999756,493.313233,613.573975,787.938232,553.368408,515.332031,479.085694,569.755616,531.588868,730.020751,NaN,455.367920
3,477.540283,653.444824,687.826660,638.047852,600.194581,542.271729,551.343262,787.571777,455.470459,730.554932,584.583252,NaN,569.662354,709.668701,679.577148,592.532959,697.166504,602.546875,734.605469,621.362304
4,535.221191,665.239747,690.097901,702.994629,690.119629,681.886963,649.891846,605.110840,776.131836,730.441650,NaN,541.546875,616.828125,608.815674,635.130616,556.743653,669.840332,458.964600,695.440918,894.776367

In [24]:
# original dataframes to be used in task 1, for reference
# hbnd_df
# sasa_ub_df
# otw_binding_df
# sasa_bnd_df
# sasa_bndwh_df
# sasa_bnd_fcc_df

#########################################################

# Normalize audio channels to between -1.0 and +1.0
# audio /= np.max(np.abs(audio),axis=0) #this normalizes to +1.0 and 0.0
# d = 2.*(a - np.min(a))/np.ptp(a)-1 #use this instead, it works better

#normalized = (x-min(x))/(max(x)-min(x)) -> normalizes pandas dataframe between (0.0,1.0)
#feat_df["Degrees"]=(feat_df["Degrees"] - feat_df["Degrees"].min())  /(feat_df["Degrees"].max() - feat_df["Degrees"].min())

Ohbnd_df = (hbnd_df.copy()).fillna(0)
#Ohbnd_df = 2.*(Ohbnd_df - np.min(Ohbnd_df))/np.ptp(Ohbnd_df)-1 #-1,1 scale
#Ohbnd_df /= np.max(np.abs(Ohbnd_df),axis=0)
#Ohbnd_df=(Ohbnd_df - Ohbnd_df.min())  /(Ohbnd_df.max() - Ohbnd_df.min()) #0,1 scale

print("hydrogen bond max: " +
      str(max( max(Ohbnd_df.max()), max(Ohbnd_df.max(axis=1)) )) +
      "    min: " + str(min( min(Ohbnd_df.min()), min(Ohbnd_df.min(axis=1)) ))
     )
#################################################################################################
Osasa_ub_df = (sasa_ub_df.copy()).fillna(0)
#Osasa_ub_df = 2.*(Osasa_ub_df - np.min(Osasa_ub_df))/np.ptp(Osasa_ub_df)-1
#Osasa_ub_df /= np.max(np.abs(Osasa_ub_df),axis=0)
Osasa_ub_df=(Osasa_ub_df - Osasa_ub_df.min())  /(Osasa_ub_df.max() - Osasa_ub_df.min())

print("SASA UB max: " +
      str(max( max(Osasa_ub_df.max()), max(Osasa_ub_df.max(axis=1)) )) +
      "    min: " + str(min( min(Osasa_ub_df.min()), min(Osasa_ub_df.min(axis=1)) ))
     )
#################################################################################################
Ootw_binding_df = ((otw_binding_df.copy()).fillna(0))
'''Ootw_binding_df = 2.*(Ootw_binding_df - np.min(Ootw_binding_df))/np.ptp(Ootw_binding_df)-1
#Ootw_binding_df /= np.max(np.abs(Ootw_binding_df),axis=0)

print("LABEL max: " +
      str(max( max(Ootw_binding_df.max()), max(Ootw_binding_df.max(axis=1)) )) +
      "    min: " + str(min( min(Ootw_binding_df.min()), min(Ootw_binding_df.min(axis=1)) ))
     )'''
#################################################################################################
Osasa_bnd_df = (sasa_bnd_df.copy()).fillna(0)
#Osasa_bnd_df = 2.*(Osasa_bnd_df - np.min(Osasa_bnd_df))/np.ptp(Osasa_bnd_df)-1
#Osasa_bnd_df /= np.max(np.abs(Osasa_bnd_df),axis=0)
Osasa_bnd_df=(Osasa_bnd_df - Osasa_bnd_df.min())  /(Osasa_bnd_df.max() - Osasa_bnd_df.min())

print("SASA bound max: " +
      str(max( max(Osasa_bnd_df.max()), max(Osasa_bnd_df.max(axis=1)) )) +
      "    min: " + str(min( min(Osasa_bnd_df.min()), min(Osasa_bnd_df.min(axis=1)) ))
     )
#################################################################################################
Osasa_bndwh_df = (sasa_bndwh_df.copy()).fillna(0)
#Osasa_bndwh_df = 2.*(Osasa_bndwh_df - np.min(Osasa_bndwh_df))/np.ptp(Osasa_bndwh_df)-1
#Osasa_bndwh_df /= np.max(np.abs(Osasa_bndwh_df),axis=0)
Osasa_bndwh_df=(Osasa_bndwh_df - Osasa_bndwh_df.min())  /(Osasa_bndwh_df.max() - Osasa_bndwh_df.min())

print("SSA whole max: " +
      str(max( max(Osasa_bndwh_df.max()), max(Osasa_bndwh_df.max(axis=1)) )) +
      "    min: " + str(min( min(Osasa_bndwh_df.min()), min(Osasa_bndwh_df.min(axis=1)) ))
     )
#################################################################################################
Osasa_bnd_fcc_df = (sasa_bnd_fcc_df.copy()).fillna(0)
#Osasa_bnd_fcc_df = 2.*(Osasa_bnd_fcc_df - np.min(Osasa_bnd_fcc_df))/np.ptp(Osasa_bnd_fcc_df)-1
#Osasa_bnd_fcc_df /= np.max(np.abs(Osasa_bnd_fcc_df),axis=0)
Osasa_bnd_fcc_df=(Osasa_bnd_fcc_df - Osasa_bnd_fcc_df.min())  /(Osasa_bnd_fcc_df.max() - Osasa_bnd_fcc_df.min())

print("SASA fcc max: " +
      str(max( max(Osasa_bnd_fcc_df.max()), max(Osasa_bnd_fcc_df.max(axis=1)) )) +
      "    min: " + str(min( min(Osasa_bnd_fcc_df.min()), min(Osasa_bnd_fcc_df.min(axis=1)) ))
     )

hydrogen bond max: 12.0    min: 0.0
SASA UB max: 1.0    min: 0.0
SASA bound max: 1.0    min: 0.0
SSA whole max: 1.0    min: 0.0
SASA fcc max: 1.0    min: 0.0

In [25]:
import numpy as np
import pandas as pd

def normalize_and_print_stats(df, df_name, scale01):
    # Copy the DataFrame, preserving NaNs
    O_df = df.copy()

    # Calculate the min and max, ignoring NaNs
    min_val = np.nanmin(O_df.values)
    max_val = np.nanmax(O_df.values)

    # Calculate the peak-to-peak (max - min) range
    ptp_val = max_val - min_val

    if(scale01):
        O_df = (O_df - min_val) / (max_val - min_val)
    else:
        # Normalize, keeping NaNs
        O_df = 2 * (O_df - min_val) / ptp_val - 1

    # Print max and min
    max_normalized = np.nanmax(O_df.values)
    min_normalized = np.nanmin(O_df.values)
    print(f"{df_name} max: {max_normalized}    min: {min_normalized}")

    return O_df

# Assuming hbnd_df, sasa_ub_df, otw_binding_df, sasa_bnd_df, sasa_bndwh_df, sasa_bnd_fcc_df are your DataFrames
#Ohbnd_df = normalize_and_print_stats(hbnd_df, "hydrogen bond", True)
Osasa_ub_df = normalize_and_print_stats(sasa_ub_df, "SASA UB", True)
#Ootw_binding_df = normalize_and_print_stats(otw_binding_df, "LABEL", False) #dun remember what this was, ignoring it lel
Osasa_bnd_df = normalize_and_print_stats(sasa_bnd_df, "SASA bound", True)
Osasa_bndwh_df = normalize_and_print_stats(sasa_bndwh_df, "SASA whole", True)
Osasa_bnd_fcc_df = normalize_and_print_stats(sasa_bnd_fcc_df, "SASA fcc", True)

SASA UB max: 1.0    min: 0.0
SASA bound max: 1.0    min: 0.0
SASA whole max: 1.0    min: 0.0
SASA fcc max: 1.0    min: 0.0

In [26]:
# Fill NaNs in each column with the mean of that column
Ootw_binding_df  = Ootw_binding_df.fillna(Ootw_binding_df.mean())

# Check if there are any NaN values left
nan_counts_after = Ootw_binding_df.isna().sum()
print("Count of NaN values in each column after filling:")
print(nan_counts_after)

Count of NaN values in each column after filling:
ALA    0
ARG    0
ASN    0
ASP    0
CYS    0
GLU    0
GLN    0
GLY    0
HIS    0
ILE    0
LEU    0
LYS    0
MET    0
PHE    0
PRO    0
SER    0
THR    0
TRP    0
TYR    0
VAL    0
dtype: int64

In [27]:
# Assuming you have a list of DataFrames, each with the shape 56x20
dataframes = [Osasa_ub_df,  Osasa_bnd_df, Osasa_bndwh_df, Osasa_bnd_fcc_df, Ohbnd_df, sasa_delta_df, Ootw_binding_df] 



# Reshaping each DataFrame
reshaped_dataframes = []
for df in dataframes:
    # Transpose each row and concatenate them
    reshaped_df = pd.concat([row.T for _, row in df.iterrows()], ignore_index=True)
    reshaped_dataframes.append(reshaped_df)
# Concatenate all reshaped DataFrames column-wise
final_df = pd.concat(reshaped_dataframes, axis=1)

print(final_df.head())

# Optionally, reset index if you want to have a simple integer index
final_df.reset_index(drop=True, inplace=True)

# Rename columns if necessary
final_df.columns = ['sasa_ub', 'sasa_bnd', 'sasa_wh', 'sasa_fcc', 'h_bnd', 'sasaDelta', 'otw_binding']  # Replace with your actual feature names

print(final_df.head())

          0         1         2         3    4           5        6
0  0.387723  0.064048  0.220288  0.446660  9.0  780.926270 -0.21010
1  0.318092  0.296536  0.407758  0.467833  9.0  619.477539 -0.23700
2  0.219625  0.163614  0.200394  0.316981  9.0  635.413818 -0.01127
3  0.144354  0.192249  0.304086  0.415365  8.0  578.694580  0.11780
4  0.240060  0.301371  0.593049  0.701483  9.0  573.823486  0.05745
    sasa_ub  sasa_bnd   sasa_wh  sasa_fcc  h_bnd   sasaDelta  otw_binding
0  0.387723  0.064048  0.220288  0.446660    9.0  780.926270     -0.21010
1  0.318092  0.296536  0.407758  0.467833    9.0  619.477539     -0.23700
2  0.219625  0.163614  0.200394  0.316981    9.0  635.413818     -0.01127
3  0.144354  0.192249  0.304086  0.415365    8.0  578.694580      0.11780
4  0.240060  0.301371  0.593049  0.701483    9.0  573.823486      0.05745

In [28]:
# Calculate the number of groups (each group has 20 rows)
num_groups = len(final_df) // 20

# Create a sequence of numbers, each repeated 20 times
# For example, [1, 1, ..., 2, 2, ..., 3, 3, ...]
group_numbers = np.repeat(np.arange(1, num_groups + 1), 20)

# Add this sequence as a new column or as an index
final_df['Group'] = group_numbers  # As a new column

In [29]:
# Amino acid residue names
residues = ['ALA', 'ARG', 'ASN', 'ASP', 'CYS', 'GLU', 'GLN', 'GLY', 'HIS', 'ILE', 
            'LEU', 'LYS', 'MET', 'PHE', 'PRO', 'SER', 'THR', 'TRP', 'TYR', 'VAL']

# Create a dictionary mapping each residue to a unique number
residue_dict = {residue: i for i, residue in enumerate(residues)}

# Assuming final_df is your DataFrame

# Calculate the number of groups (each group has 20 rows)
num_groups = len(final_df) // 20

# Create a sequence of group numbers, each repeated 20 times
group_numbers = np.repeat(np.arange(1, num_groups + 1), 20)

# Replace residue names with their corresponding values using the dictionary
encoded_residue_sequence = [residue_dict[residue] for residue in np.tile(residues, num_groups)]

# Combine group numbers and encoded residues
combined_labels = [f"{encoded_residue} " for encoded_residue, group in zip(encoded_residue_sequence, group_numbers)]

# Add combined labels as a new column or set as index
final_df['mut_TO'] = combined_labels  # As a new column
# OR
# final_df.index = pd.Index(combined_labels, name='mut_TO')  # Set as index

In [30]:
# Corrected list of column names for reordering
new_order = ['Group', 'mut_TO', 'sasa_ub', 'sasa_bnd', 'sasa_wh', 'sasa_fcc', 'h_bnd', 'sasaDelta', 'otw_binding']

# Verify that all these columns exist in your DataFrame
missing_cols = [col for col in new_order if col not in final_df.columns]
if missing_cols:
    print("The following columns are missing:", missing_cols)
else:
    # Reorder the DataFrame
    final_df = final_df[new_order]

In [31]:
final_df.head(25)

,Group,mut_TO,sasa_ub,sasa_bnd,sasa_wh,sasa_fcc,h_bnd,sasaDelta,otw_binding
0,1,0,0.387723,0.064048,0.220288,0.446660,9.0,780.926270,-0.21010
1,1,1,0.318092,0.296536,0.407758,0.467833,9.0,619.477539,-0.23700
2,1,2,0.219625,0.163614,0.200394,0.316981,9.0,635.413818,-0.01127
3,1,3,0.144354,0.192249,0.304086,0.415365,8.0,578.694580,0.11780
4,1,4,0.240060,0.301371,0.593049,0.701483,9.0,573.823486,0.05745
5,1,5,0.233074,0.380401,0.363716,0.302613,10.0,528.156250,0.10960
6,1,6,0.245534,0.449205,0.458047,0.423238,9.0,498.638916,0.00000
7,1,7,0.294556,0.243664,0.270170,0.371260,8.0,634.449219,-0.10040
8,1,8,0.264045,0.374808,0.357982,0.360532,8.0,548.219726,-0.06150
9,1,9,0.266057,0.339635,0.386797,0.384922,10.0,567.938720,-0.06040
10,1,10,0.318658,0.443037,0.426339,0.359939,10.0,542.287110,-0.12550
11,1,11,0.314748,0.317033,0.515979,0.564237,9.0,606.787110,-0.13380
12,1,12,NaN,0.467699,0.606400,0.599910,10.0,NaN,-0.16610
13,1,13,0.246517,0.358946,0.548364,0.594310,10.0,546.930908,-0.25560
14,1,14,0.346340,0.381645,0.322128,0.284807,9.0,590.053711,-0.17520
15,1,15,0.288519,0.334297,0.501829,0.527704,10.0,583.168213,-0.09686
16,1,16,0.246405,NaN,NaN,NaN,0.0,NaN,-0.12380
17,1,17,0.334392,0.293219,0.487457,0.557797,8.0,630.234375,-0.16450
18,1,18,0.294419,0.345337,0.554986,0.574284,8.0,580.586182,-0.14230
19,1,19,0.144408,0.300521,0.462827,0.493761,9.0,521.445557,-0.01975
20,2,0,0.250888,0.425688,0.798370,0.877576,10.0,514.036866,-0.53270
21,2,1,0.394248,0.533423,0.978259,0.985048,5.0,536.218261,0.42440
22,2,2,0.225374,0.379136,0.397159,0.385589,8.0,524.572754,0.15390
23,2,3,0.284387,0.246766,0.438378,0.562541,9.0,627.192383,3.19700
24,2,4,0.399900,0.250525,0.529115,0.643841,9.0,688.999756,-0.14580

In [32]:
# final_df.replace(0, pd.NA, inplace=True)

# # Drop rows with any NaN values (which were originally 0s)
final_df.dropna(inplace=True)

# # If you need to reset the index after dropping rows
final_df.reset_index(drop=True, inplace=True)

In [33]:
print(f"Are there any NaN values in the DataFrame? {final_df.isna().any().any()}")

Are there any NaN values in the DataFrame? False

In [34]:
residues = ['ALA', 'ARG', 'ASN', 'ASP', 'CYS', 'GLU', 'GLN', 'GLY', 'HIS', 'ILE', 
            'LEU', 'LYS', 'MET', 'PHE', 'PRO', 'SER', 'THR', 'TRP', 'TYR', 'VAL']

# Create a dictionary with residue names as keys and their indices as values
residue_dict = {residue: i for i, residue in enumerate(residues)}

print(residue_dict)

{'ALA': 0, 'ARG': 1, 'ASN': 2, 'ASP': 3, 'CYS': 4, 'GLU': 5, 'GLN': 6, 'GLY': 7, 'HIS': 8, 'ILE': 9, 'LEU': 10, 'LYS': 11, 'MET': 12, 'PHE': 13, 'PRO': 14, 'SER': 15, 'THR': 16, 'TRP': 17, 'TYR': 18, 'VAL': 19}

In [35]:
final_df.head(10)

,Group,mut_TO,sasa_ub,sasa_bnd,sasa_wh,sasa_fcc,h_bnd,sasaDelta,otw_binding
0,1,0,0.387723,0.064048,0.220288,0.446660,9.0,780.926270,-0.21010
1,1,1,0.318092,0.296536,0.407758,0.467833,9.0,619.477539,-0.23700
2,1,2,0.219625,0.163614,0.200394,0.316981,9.0,635.413818,-0.01127
3,1,3,0.144354,0.192249,0.304086,0.415365,8.0,578.694580,0.11780
4,1,4,0.240060,0.301371,0.593049,0.701483,9.0,573.823486,0.05745
5,1,5,0.233074,0.380401,0.363716,0.302613,10.0,528.156250,0.10960
6,1,6,0.245534,0.449205,0.458047,0.423238,9.0,498.638916,0.00000
7,1,7,0.294556,0.243664,0.270170,0.371260,8.0,634.449219,-0.10040
8,1,8,0.264045,0.374808,0.357982,0.360532,8.0,548.219726,-0.06150
9,1,9,0.266057,0.339635,0.386797,0.384922,10.0,567.938720,-0.06040

In [36]:
# # Suppose you have a DataFrame 'df' and want to slice from 'start_column_name' to the end
start_column_name = 'otw_binding'

# # Get the index of the 'start_column_name'
start_column_index = final_df.columns.get_loc(start_column_name)

# shuffle the data
final_df = final_df.sample(frac=1).reset_index(drop=True)

# # Slice the DataFrame from 'start_column_name' to the end
label_df = final_df.iloc[:, start_column_index:]
feat_df = final_df.iloc[:,:start_column_index]

In [38]:
feat_df

      Group mut_TO   sasa_ub  sasa_bnd   sasa_wh  sasa_fcc  h_bnd   sasaDelta
0        42     1   0.344199  0.264496  0.410532  0.470904    8.0  650.845948
1        48     9   0.317736  0.371311  0.401971  0.420353   10.0  579.723144
2         7    12   0.598616  0.607001  0.574103  0.461226    9.0  610.163818
3        29     6   0.436809  0.405079  0.555892  0.577662   10.0  627.621582
4        10     7   0.308660  0.137411  0.332615  0.450166   10.0  698.449219
...     ...    ...       ...       ...       ...       ...    ...         ...
1037      7     6   0.587026  0.423514  0.655134  0.674133    8.0  700.832032
1038     43     7   0.451169  0.417582  0.668689  0.672987    4.0  628.937744
1039     14    18   0.294945  0.206239  0.449486  0.555157    8.0  654.463135
1040     35    10   0.491849  0.418771  0.535053  0.538228    8.0  650.776123
1041     23    10   0.364746  0.405830  0.354712  0.344609    9.0  587.424805

[1042 rows x 8 columns]

In [39]:
mut_impact_df = feat_df.pivot(index='Group', columns='mut_TO', values='sasaDelta')
mut_impact_df.head(5)

KeyError: 'DeltaSASA'

In [ ]:
print("Count of NaN values in each column:\n", mut_impact_df.isna().sum(axis=1))

In [ ]:
correlation_matrix = mut_impact_df.corr(method='pearson')
print("Size of the correlation matrix:", correlation_matrix.shape)

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming 'correlation_matrix' is your DataFrame with correlations

# Set up the matplotlib figure
plt.figure(figsize=(10, 8))

# Draw the heatmap
sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap='coolwarm', center=0)

# Adjust the plot
plt.title('Correlation Matrix Heatmap')
plt.xticks(rotation=45)
plt.yticks(rotation=45)

# Show the plot
plt.show()

In [ ]:
# Flatten the correlation matrix and filter out self-correlations
correlation_values = correlation_matrix.values.flatten()
correlation_values = correlation_values[correlation_values != 1]

# Plot histogram
plt.hist(correlation_values, bins=50, color='blue', edgecolor='black')
plt.title('Distribution of Correlation Values')
plt.xlabel('Correlation')
plt.ylabel('Frequency')
plt.show()

In [ ]:
threshold = np.mean(correlation_values)
print(threshold)
correlation_matrix.head()

In [ ]:
import networkx as nx

In [ ]:
G = nx.Graph()

# Assuming feat_df is your dataframe with the nodes and their attributes
# Assuming correlation_matrix is a pandas DataFrame with your correlations

# Add nodes with all attributes from feat_df, represented by 'Group' and 'mut_TO'
for idx, row in feat_df.iterrows():
    node_label = (row['Group'], row['mut_TO'])
    G.add_node(node_label, attr_dict=row.to_dict())

# Define a threshold for adding edges
threshold = 0.1  # Adjust this threshold as needed

# Add edges based on the correlation matrix and threshold, but exclude edges where mut_TO is the same
for i, row_i in feat_df.iterrows():
    for j, row_j in feat_df.iterrows():
        if i != j and row_i['mut_TO'] != row_j['mut_TO']:  # avoid self-loops and edges with same mut_TO
            corr_value = correlation_matrix.at[row_i['mut_TO'], row_j['mut_TO']]
            if corr_value > threshold:
                G.add_edge((row_i['Group'], row_i['mut_TO']), (row_j['Group'], row_j['mut_TO']), weight=corr_value)

# List every edge above the threshold
edges_above_threshold = []
for (node1, node2, data) in G.edges(data=True):
    if data['weight'] > threshold:
        node1_group, node1_mut_TO = node1
        node2_group, node2_mut_TO = node2
        edge_weight = data['weight']
        edges_above_threshold.append({
            'node1_group': node1_group,
            'node1_mut_TO': node1_mut_TO,
            'node2_group': node2_group,
            'node2_mut_TO': node2_mut_TO,
            'edge_weight': edge_weight
        })
print("Number of edges in the graph:", G.number_of_edges())
# Output the edges information
for edge in edges_above_threshold:
    print(edge)

In [ ]:
plt.figure(figsize=(12, 8))
pos = nx.spring_layout(G)  # positions for all nodes
nx.draw_networkx_nodes(G, pos, node_size=700)
nx.draw_networkx_edges(G, pos, width=2)
nx.draw_networkx_labels(G, pos, font_size=5, font_family='sans-serif')
plt.axis('off')
plt.show()

In [ ]:
'''
page rank:					networkx.pagerank(G)
degree:						Graph.degree( optional:specific nodes), returns a DegreeView
strength:					?
eigenvector centrality:		networkx.eigenvector_centrality(G), return nodes dictionary
clustering coefficient:		nx.clustering(G), return nodes dictionary
closeness centrality(?):	nx.closeness_centrality(G), return nodes dictionary
normalized edge weigts:		?
'''

PageRank = nx.pagerank(G) #node dictionary is returned (also 1042 long list basically)
degrees = G.degree() #degreeView item is returned (1042 item long list basically)
eigenCentrality = nx.eigenvector_centrality(G) #node dictionary is returned (also 1042 long list basically)
clusteringCoeff = nx.clustering(G) #node dictionary is returned (also 1042 long list basically)
closenessCentrality = nx.closeness_centrality(G) #node dictionary is returned (also 1042 long list basically)

feat_df.head(5)

In [ ]:
'''
page rank:					networkx.pagerank(G), return nodes dictionary						PageRank
degree:						Graph.degree( optional:specific nodes), returns a DegreeView		degrees
eigenvector centrality:		networkx.eigenvector_centrality(G), return nodes dictionary			eigenCentrality
clustering coefficient:		nx.clustering(G), return nodes dictionary							clusteringCoeff
closeness centrality(?):	nx.closeness_centrality(G), return nodes dictionary					closenessCentrality
'''
arr = []
# 55 x 19
for i in range(len(feat_df)):
    groupN = feat_df["Group"].iloc[i]
    mutN = feat_df["mut_TO"].iloc[i]
    arr.append(PageRank[((groupN, f'{mutN}'))])
print(len(arr))
feat_df.insert(8, "Page Rank", arr)
################################################################
arr = []
# 55 x 19
for i in range(len(feat_df)):
    groupN = feat_df["Group"].iloc[i]
    mutN = feat_df["mut_TO"].iloc[i]
    arr.append(eigenCentrality[((groupN, f'{mutN}'))])
print(len(arr))
feat_df.insert(9, "Eigen Centrality", arr)
################################################################
arr = []
# 55 x 19
for i in range(len(feat_df)):
    groupN = feat_df["Group"].iloc[i]
    mutN = feat_df["mut_TO"].iloc[i]
    arr.append(clusteringCoeff[((groupN, f'{mutN}'))])
print(len(arr))
feat_df.insert(10, "Clustering Coefficient", arr)
################################################################
arr = []
# 55 x 19
for i in range(len(feat_df)):
    groupN = feat_df["Group"].iloc[i]
    mutN = feat_df["mut_TO"].iloc[i]
    arr.append(closenessCentrality[((groupN, f'{mutN}'))])
print(len(arr))
feat_df.insert(11, "closenessCentrality", arr)
################################################################
degree_values = [v for k, v in degrees]
print(len(degree_values))
feat_df.insert(12, "Degrees", degree_values)

In [ ]:
'''#normalized = (x-min(x))/(max(x)-min(x))
feat_df["Degrees"]=(feat_df["Degrees"] - feat_df["Degrees"].min())  /(feat_df["Degrees"].max() - feat_df["Degrees"].min())'''
feat_df.head(10)

In [ ]:
for i in feat_df.columns:
    print(f"{i} (min, max): ({feat_df[i].min()}, {feat_df[i].max()})")

In [ ]:
# Get one hot encoding of columns B
one_hot = pd.get_dummies(feat_df['mut_TO'])
# Drop column B as it is now encoded
feat_df = feat_df.drop('mut_TO',axis = 1)
# Join the encoded df
feat_df = feat_df.join(one_hot)
feat_df.head()
print(feat_df.columns)

In [ ]:
feat_df = feat_df.sample(frac=1).reset_index(drop=True)
feat_df